---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  manifests_path: puppet/manifests
  modules_path: puppet/modules
  hiera_data_path: puppet/data
  hiera_config_path: puppet/hiera.yaml
  hiera_deep_merge: true
  vm_hostname: 'test'
  require_chef_for_busser: false
  require_puppet_repo: false
  puppet_logdest:
    - 'console'
  #http_proxy: 'http://192.168.1.3:3142' # Disable this unless you use apt-cacher-ng or something that caches

platforms:
  - name: ubuntu1464
    driver:
      box: ubuntu1464-puppet
      box_url: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-puppet/versions/1.0.1/providers/virtualbox.box

suites:
  - name: default
    manifest: site.pp
    driver_config:
      network:
        - ["private_network", {ip: "192.168.33.2"}]
      customize:
        memory: 1024
        cpus: 2

  - name: tlp
    manifest: site.pp
    driver_config:
      network:
        - ["private_network", {ip: "192.168.33.2"}]
      customize:
        memory: 1024
        cpus: 2
